### PR TITLE
Upgrade to svgo 1

### PR DESCRIPTION
**Pull request by theverything**
- Converted the plugin to use promises
- Pulled in changes from https://github.com/ben-eb/gulp-svgmin/pull/77/commits/23416c3

### CODE REVIEW

**Comment by theverything** [comment]
Tests are passing in all versions of node except for `0.12`. This is due to the fact that `svgo@1.0.0` uses promises.

**Comment by adamcoulombe** [comment]
SVGo is now @1.0.4 . I am also looking for an update to gulp-svgmin and cant figure out how to get my repo to load an updated svgo binary

**Comment by theverything** [comment]
@ben-eb any idea of when you might review this?

**Comment by theverything** [comment]
@ben-eb checking back in again. Do you think this will this ever get merged?

**Comment by rejas** [comment]
hi @theverything took your PR and merged it into my cleanup branch, so yes, it will get merged soon (will give @ben-eb a day to take alook at it before doing it though)

**Comment by rejas** [comment]
Release is done, only need to to be published to the npm registry @ben-eb

**Comment by ben-eb** [comment]
@rejas You have publish access! 😃

**Comment by rejas** [comment]
@ben-eb Publish is done :-)

**Pull request closed without merging**
