### PR TITLE
Fix bug

### PR DESCRIPTION
**Pull request by corollari**
## Bug
[This svg image](https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/1x1/hk.svg) will cause the following error when applied to gulp-svgmin:
```
/home/corollari/projects/neo-mon/node_modules/svgo/plugins/convertPathData.js:766
        if (data[i].toFixed(precision) != data[i]) {
                    ^

TypeError: Cannot read property 'toFixed' of undefined
    at strongRound (/home/corollari/projects/neo-mon/node_modules/svgo/plugins/convertPathData.js:766:21)
    at /home/corollari/projects/neo-mon/node_modules/svgo/plugins/convertPathData.js:424:17
    at Array.filter (<anonymous>)
    at filters (/home/corollari/projects/neo-mon/node_modules/svgo/plugins/convertPathData.js:272:17)
    at Object.exports.fn (/home/corollari/projects/neo-mon/node_modules/svgo/plugins/convertPathData.js:79:20)
    at /home/corollari/projects/neo-mon/node_modules/svgo/lib/svgo/plugins.js:59:45
    at Array.filter (<anonymous>)
    at monkeys (/home/corollari/projects/neo-mon/node_modules/svgo/lib/svgo/plugins.js:46:39)
    at /home/corollari/projects/neo-mon/node_modules/svgo/lib/svgo/plugins.js:66:17
    at Array.filter (<anonymous>)
```

## Solution
As discovered in [this issue](https://github.com/svg/svgo/issues/990) the problem seems to stem from the svgo dependency, which I have updated to a problem-free version. I haven't updated it to the latest version as it seems the same issue has reappeared in later versions (I haven't tested it tho).

### CODE REVIEW

**Comment by rejas** [comment]
Thx for the PR @corollari but could you check why the travis builds fails?

**Comment by corollari** [comment]
Just fixed the travis build :+1:

**Comment by madhaze** [comment]
Did this ever make it into a release?  it looks like svgo is still at `1.2.1` on `2.2.0` release.

**Comment by rejas** [comment]
You are right, this wasnt released yet. 
Just published v3.0.0 with this fix and other stuff. Enjoy!

**Pull request merged**
